name: Luacheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  luacheck:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Luacheck
        uses: lunarmodules/luacheck@v0
