name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: LuaRocks upload
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Extract module revision
        id: vars
        run: echo "modrev=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      - name: LuaRocks Upload
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        run:
          docker run --rm -v $(pwd):/opt/app -w /opt/app imolein/luarocks:5.3-alpine luarocks upload rockspecs/enapter-ucm-${{ steps.vars.outputs.modrev }}-1.rockspec --api-key "${LUAROCKS_API_KEY}"
