name: StyLua

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  stylua:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Formatting
        uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.16.1
          args: --check --allow-hidden .
